version: '3'
services:
  vue-ui:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./:/usr/src/app/kudy-shapes
       - /usr/src/app/node_modules